name: flutter_app
description: Metro Router

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  flutter_map: ^8.2.1
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true